import type { BuilderItem, SiteContent } from "@/types";

export const SITE = {
  name: "La Piccola Deli",
  established: 2020,
  tagline: "Italian deli favourites — panini, piadina & fresh lasagna",
  rating: 4.8,
  reviewCount: 120,
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://piccola.pradeepandigital.workers.dev",
  logo: "",
  instagram: "https://www.instagram.com/",
  instagramHandle: "@lapiccoladeli",
};

/** Menu plate photography (food crops only) */
export const PLATES = {
  salutarePanini: "/images/menu/salutare-panini.jpg",
  parmaPanini: "/images/menu/parma-panini.jpg",
  chickenPanini: "/images/menu/chicken-panini.jpg",
  italianoVegPanini: "/images/menu/italiano-veg-panini.jpg",
  salutarePiadina: "/images/menu/salutare-piadina.jpg",
  parmaPiadina: "/images/menu/parma-piadina.jpg",
  chickenPiadina: "/images/menu/chicken-piadina.jpg",
  vegPiadina: "/images/menu/veg-piadina.jpg",
  beefLasagna: "/images/menu/beef-lasagna.jpg",
  spinachLasagna: "/images/menu/spinach-lasagna.jpg",
  pestoBasilLasagna: "/images/menu/pesto-basil-lasagna.jpg",
  chickenEscalope: "/images/menu/chicken-escalope.jpg",
  meatballs: "/images/menu/meatballs.jpg",
  aubergineParmigiana: "/images/menu/aubergine-parmigiana.jpg",
} as const;

export const GALLERY_SHOTS = {
  hero: "/images/hero-interior.jpg",
  parma: PLATES.parmaPanini,
  lasagna: PLATES.beefLasagna,
  meatballs: PLATES.meatballs,
  aubergine: PLATES.aubergineParmigiana,
  piadina: PLATES.parmaPiadina,
  escalope: PLATES.chickenEscalope,
  pesto: PLATES.pestoBasilLasagna,
} as const;

export const defaultContent: SiteContent = {
  phone: "0000 000 0000",
  email: "hello@lapiccoladeli.co.uk",
  address: {
    line1: "Address coming soon",
    line2: "",
    city: "London",
    postcode: "",
    country: "United Kingdom",
  },
  specialOfTheDay: {
    name: "Parma Panini",
    description:
      "Crusty panini with Parma ham, buffalo mozzarella, salad and tomato — a Piccola classic.",
    price: 8.5,
  },
  openingHours: [
    { day: "Monday", hours: "9:00 AM - 5:00 PM" },
    { day: "Tuesday", hours: "9:00 AM - 5:00 PM" },
    { day: "Wednesday", hours: "9:00 AM - 5:00 PM" },
    { day: "Thursday", hours: "9:00 AM - 5:00 PM" },
    { day: "Friday", hours: "9:00 AM - 5:00 PM" },
    { day: "Saturday", hours: "9:00 AM - 4:00 PM" },
    { day: "Sunday", hours: "Closed", closed: true },
  ],
  featuredDishIds: [
    "parma-panini",
    "pesto-basil-lasagna",
    "meatballs",
    "aubergine-parmigiana",
  ],
  announcements: [
    {
      id: "a1",
      text: "Collect or eat in — order ahead and we’ll prepare it fresh for you",
      active: true,
    },
  ],
  menuItems: [
    {
      id: "salutare-panini",
      name: "Salutare Panini",
      description: "Bread, cooked ham, buffalo mozzarella, salad and tomato.",
      price: 7.5,
      category: "panini",
      image: PLATES.salutarePanini,
      favourite: true,
      ingredients: ["Bread", "Cooked ham", "Buffalo mozzarella", "Salad", "Tomato"],
    },
    {
      id: "parma-panini",
      name: "Parma Panini",
      description: "Bread, Parma ham, buffalo mozzarella, salad and tomato.",
      price: 8.5,
      category: "panini",
      image: PLATES.parmaPanini,
      favourite: true,
      featured: true,
      ingredients: ["Bread", "Parma ham", "Buffalo mozzarella", "Salad", "Tomato"],
      story: "Our Parma panini is the one regulars order without looking at the board.",
      chefNote: "Ask for extra rocket if you like it peppery.",
    },
    {
      id: "chicken-panini",
      name: "Chicken Panini",
      description: "Bread, chicken escalope, mayo, salad and tomato.",
      price: 8.0,
      category: "panini",
      image: PLATES.chickenPanini,
      favourite: true,
      ingredients: ["Bread", "Chicken escalope", "Mayo", "Salad", "Tomato"],
    },
    {
      id: "italiano-veg-panini",
      name: "Italiano (Veg) Panini",
      description: "Bread, tomato, mozzarella, basil and pesto sauce.",
      price: 7.5,
      category: "panini",
      image: PLATES.italianoVegPanini,
      favourite: true,
      ingredients: ["Bread", "Tomato", "Mozzarella", "Basil", "Pesto sauce"],
    },
    {
      id: "salutare-piadina",
      name: "Salutare Piadina",
      description: "Flatbread, cooked ham, buffalo mozzarella, salad and tomato.",
      price: 7.5,
      category: "piadina",
      image: PLATES.salutarePiadina,
      favourite: true,
      ingredients: ["Bread", "Cooked ham", "Buffalo mozzarella", "Salad", "Tomato"],
    },
    {
      id: "parma-piadina",
      name: "Parma Piadina",
      description: "Flatbread, Parma ham, buffalo mozzarella, salad and tomato.",
      price: 8.5,
      category: "piadina",
      image: PLATES.parmaPiadina,
      favourite: true,
      featured: true,
      ingredients: ["Bread", "Parma ham", "Buffalo mozzarella", "Salad", "Tomato"],
      story: "Thin grilled piadina wrapped around proper Parma and fresh mozzarella.",
    },
    {
      id: "chicken-piadina",
      name: "Chicken Piadina",
      description: "Flatbread, chicken escalope, mayo, salad and tomato.",
      price: 8.0,
      category: "piadina",
      image: PLATES.chickenPiadina,
      favourite: true,
      ingredients: ["Bread", "Chicken escalope", "Mayo", "Salad", "Tomato"],
    },
    {
      id: "veg-piadina",
      name: "Veg Piadina",
      description: "Flatbread, tomato, mozzarella, basil and pesto sauce.",
      price: 7.5,
      category: "piadina",
      image: PLATES.vegPiadina,
      favourite: true,
      ingredients: ["Bread", "Tomato", "Mozzarella", "Basil", "Pesto sauce"],
    },
    {
      id: "beef-lasagna",
      name: "Beef Lasagna",
      description: "Ground beef, bolognese sauce, tomato sauce.",
      price: 9.5,
      category: "lasagna",
      image: PLATES.beefLasagna,
      favourite: true,
      featured: true,
      ingredients: ["Ground beef", "Bolognese sauce", "Tomato sauce"],
      story: "Slow-layered beef lasagna — comfort food done the Italian way.",
      chefNote: "Perfect for collect — reheats beautifully.",
    },
    {
      id: "spinach-lasagna",
      name: "Spinach Lasagna",
      description: "Spinach, ricotta, tomato sauce, mozzarella.",
      price: 9.0,
      category: "lasagna",
      image: PLATES.spinachLasagna,
      favourite: true,
      ingredients: ["Spinach", "Ricotta", "Tomato sauce", "Mozzarella"],
    },
    {
      id: "pesto-basil-lasagna",
      name: "Pesto-Basil Lasagna",
      description: "Basil pesto, mozzarella cheese, green beans.",
      price: 9.5,
      category: "lasagna",
      image: PLATES.pestoBasilLasagna,
      favourite: true,
      featured: true,
      ingredients: ["Basil pesto", "Mozzarella", "Green beans"],
      story: "Bright pesto and mozzarella between soft pasta sheets.",
    },
    {
      id: "chicken-escalope",
      name: "Chicken Escalope",
      description: "Breaded chicken, mayo.",
      price: 8.5,
      category: "mains",
      image: PLATES.chickenEscalope,
      favourite: true,
      ingredients: ["Breaded chicken", "Mayo"],
    },
    {
      id: "meatballs",
      name: "Meatballs",
      description: "Beef, tomato sauce and bolognese sauce.",
      price: 8.5,
      category: "mains",
      image: PLATES.meatballs,
      favourite: true,
      featured: true,
      ingredients: ["Beef", "Tomato sauce", "Bolognese sauce"],
      story: "House meatballs in a rich tomato and bolognese sauce.",
    },
    {
      id: "aubergine-parmigiana",
      name: "Aubergine Parmigiana",
      description: "Grilled aubergine, tomato sauce, parmigiana.",
      price: 8.5,
      category: "mains",
      image: PLATES.aubergineParmigiana,
      favourite: true,
      featured: true,
      ingredients: ["Grilled aubergine", "Tomato sauce", "Parmigiana"],
      story: "Layered aubergine with tomato and melted cheese — a vegetarian favourite.",
    },
  ],
  reviews: [
    {
      id: "r1",
      name: "Sofia R.",
      rating: 5,
      text: "The Parma panini tastes like Italy. Fresh mozzarella, proper ham — we’ll be back every week.",
      date: "2 weeks ago",
      avatar:
        "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
    },
    {
      id: "r2",
      name: "Marco L.",
      rating: 5,
      text: "Beef lasagna for collect was perfect. Still warm, still generous. Real deli energy.",
      date: "1 month ago",
      avatar:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    },
    {
      id: "r3",
      name: "Elena P.",
      rating: 5,
      text: "Veg piadina and pesto lasagna — light, fragrant, exactly what I wanted for lunch.",
      date: "3 weeks ago",
      avatar:
        "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    },
    {
      id: "r4",
      name: "James T.",
      rating: 4,
      text: "Meatballs are outstanding. Friendly counter, quick collect, solid coffee nearby.",
      date: "1 week ago",
      avatar:
        "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    },
  ],
  gallery: [
    {
      id: "g1",
      src: PLATES.parmaPanini,
      alt: "Parma panini",
      span: "wide",
    },
    {
      id: "g2",
      src: PLATES.meatballs,
      alt: "Meatballs in tomato sauce",
      span: "normal",
    },
    {
      id: "g3",
      src: PLATES.beefLasagna,
      alt: "Beef lasagna",
      span: "tall",
    },
    {
      id: "g4",
      src: PLATES.parmaPiadina,
      alt: "Parma piadina",
      span: "normal",
    },
    {
      id: "g5",
      src: PLATES.aubergineParmigiana,
      alt: "Aubergine parmigiana",
      span: "wide",
    },
    {
      id: "g6",
      src: PLATES.chickenEscalope,
      alt: "Chicken escalope",
      span: "normal",
    },
    {
      id: "g7",
      src: PLATES.pestoBasilLasagna,
      alt: "Pesto-basil lasagna",
      span: "tall",
    },
    {
      id: "g8",
      src: PLATES.salutarePanini,
      alt: "Salutare panini",
      span: "normal",
    },
    {
      id: "g9",
      src: PLATES.vegPiadina,
      alt: "Veg piadina",
      span: "wide",
    },
    {
      id: "g10",
      src: PLATES.spinachLasagna,
      alt: "Spinach lasagna",
      span: "normal",
    },
  ],
};

/** Kept for type compatibility; builder section removed from homepage */
export const builderItems: BuilderItem[] = [];

export const navLinks = [
  { href: "#home", label: "Home" },
  { href: "#story", label: "Story" },
  { href: "#favourites", label: "Favourites" },
  { href: "#menu", label: "Menu" },
  { href: "#gallery", label: "Gallery" },
  { href: "#visit", label: "Visit" },
  { href: "#reserve", label: "Order" },
];

export const timeline = [
  {
    year: "Beginning",
    title: "A little deli with big flavour",
    text: "La Piccola Deli opened with a simple idea — honest Italian lunch food made fresh every day.",
  },
  {
    year: "Kitchen",
    title: "Panini, piadina, lasagna",
    text: "Grilled breads, proper fillings, and recipes that feel like home for locals and neighbours.",
  },
  {
    year: "Today",
    title: "Order ahead, eat in or collect",
    text: "Reserve a table or collect your order — we’ll prepare it fresh for your time.",
  },
];

export const instagramPosts = [
  PLATES.parmaPanini,
  PLATES.meatballs,
  PLATES.beefLasagna,
  PLATES.parmaPiadina,
  PLATES.aubergineParmigiana,
  PLATES.pestoBasilLasagna,
];
