/** Auto-mapped original plate photos by dish name */
export const DISH_PHOTOS: Record<string, string> = {
  "Arancino": "/images/dishes/arancino.jpg",
  "Arrabbiata Pasta": "/images/dishes/arrabbiata-pasta.jpg",
  "Avocado On Toast": "/images/dishes/avocado-on-toast.jpg",
  "Bolognese Pasta": "/images/dishes/bolognese-pasta.jpg",
  "Butternut Squash Soup": "/images/dishes/butternut-squash-soup.jpg",
  "Chicken Caesar Salad": "/images/dishes/chicken-caesar-salad.jpg",
  "Cous Cous Chicken Main": "/images/dishes/cous-cous-chicken-main.jpg",
  "Cous Cous Main": "/images/dishes/cous-cous-main.jpg",
  "Croissant Apricot": "/images/dishes/croissant-apricot.jpg",
  "Croissant Chocolate": "/images/dishes/croissant-chocolate.jpg",
  "Croissant Custard": "/images/dishes/croissant-custard.jpg",
  "Croissant Pistachio": "/images/dishes/croissant-pistachio.jpg",
  "Croissant Plain": "/images/dishes/croissant-plain.jpg",
  "Focaccia Salame And Scamorza": "/images/dishes/focaccia-salame-and-scamorza.jpg",
  "Frittata Homemade": "/images/dishes/frittata-homemade.jpg",
  "Gnocchi Al Pesto": "/images/dishes/gnocchi-al-pesto.jpg",
  "Gnocchi Alla Sorrentina": "/images/dishes/gnocchi-alla-sorrentina.jpg",
  "Greek Yoghurt Granola": "/images/dishes/greek-yoghurt-granola.jpg",
  "Ham And Cheese Croissant": "/images/dishes/ham-and-cheese-croissant.jpg",
  "Lasagna Al Pesto": "/images/dishes/lasagna-al-pesto.jpg",
  "Lasagna Bolognese": "/images/dishes/lasagna-bolognese.jpg",
  "Leek And Potatoes Soup": "/images/dishes/leek-and-potatoes-soup.jpg",
  "Marinated Roast Chicken Breast With Potatoes": "/images/dishes/marinated-roast-chicken-breast-with-potatoes.jpg",
  "Mini Sausage And Potatoes": "/images/dishes/mini-sausage-and-potatoes.jpg",
  "Mozzarella And Tomato Croissant": "/images/dishes/mozzarella-and-tomato-croissant.jpg",
  "Panino Al Cotto": "/images/dishes/panino-al-cotto.jpg",
  "Panino Al Crudo": "/images/dishes/panino-al-crudo.jpg",
  "Panino Salmon And Cream Cheese": "/images/dishes/panino-salmon-and-cream-cheese.jpg",
  "Panzerotto Mediterraneo": "/images/dishes/panzerotto-mediterraneo.jpg",
  "Pasqualina": "/images/dishes/pasqualina.jpg",
  "Pasta Al Pesto": "/images/dishes/pasta-al-pesto.jpg",
  "Pasta Al Pomodoro": "/images/dishes/pasta-al-pomodoro.jpg",
  "Pasta Boscaiola": "/images/dishes/pasta-boscaiola.jpg",
  "Pasta Salsiccia Ragu": "/images/dishes/pasta-salsiccia-ragu.jpg",
  "Pizza Bianca": "/images/dishes/pizza-bianca.jpg",
  "Pizza Margherita": "/images/dishes/pizza-margherita.jpg",
  "Roastbeef Rocket And Parmesan": "/images/dishes/roastbeef-rocket-and-parmesan.jpg",
  "Valdostana": "/images/dishes/valdostana.jpg"
} as const;
