/** Auto-mapped original plate photos by dish name */
export const DISH_PHOTOS: Record<string, string> = {
  "Americano": "/images/dishes/americano.jpg",
  "Arancino": "/images/dishes/arancino.jpg",
  "Arrabbiata Pasta": "/images/dishes/arrabbiata-pasta.jpg",
  "Aubergine Parmigiana": "/images/dishes/aubergine-parmigiana.jpg",
  "Avocado On Toast": "/images/dishes/avocado-on-toast.jpg",
  "Bolognese Pasta": "/images/dishes/bolognese-pasta.jpg",
  "Bresaola Carpaccio": "/images/dishes/bresaola-carpaccio.jpg",
  "Butternut Squash Soup": "/images/dishes/butternut-squash-soup.jpg",
  "Camomile": "/images/dishes/camomile.jpg",
  "Caponata Di Melanzane": "/images/dishes/caponata-di-melanzane.jpg",
  "Cappuccino": "/images/dishes/cappuccino.jpg",
  "Chicken Caesar Salad": "/images/dishes/chicken-caesar-salad.jpg",
  "Chicken Cotoletta With Salad": "/images/dishes/chicken-cotoletta-with-salad.jpg",
  "Coca Cola In Can": "/images/dishes/coca-cola-in-can.jpg",
  "Cous Cous Chicken Main": "/images/dishes/cous-cous-chicken-main.jpg",
  "Cous Cous Main": "/images/dishes/cous-cous-main.jpg",
  "Croissant Apricot": "/images/dishes/croissant-apricot.jpg",
  "Croissant Chocolate": "/images/dishes/croissant-chocolate.jpg",
  "Croissant Custard": "/images/dishes/croissant-custard.jpg",
  "Croissant Pistachio": "/images/dishes/croissant-pistachio.jpg",
  "Croissant Plain": "/images/dishes/croissant-plain.jpg",
  "Diet Coke In Can": "/images/dishes/diet-coke-in-can.jpg",
  "Double Espresso": "/images/dishes/double-espresso.jpg",
  "Double Macchiato": "/images/dishes/double-macchiato.jpg",
  "Earl Grey": "/images/dishes/earl-grey.jpg",
  "English Breakfast Tea": "/images/dishes/english-breakfast-tea.jpg",
  "Espresso": "/images/dishes/espresso.jpg",
  "Estathe Lemon": "/images/dishes/estathe-lemon.jpg",
  "Estathe Peach": "/images/dishes/estathe-peach.jpg",
  "Flat White": "/images/dishes/flat-white.jpg",
  "Focaccia Chicken Escalope": "/images/dishes/focaccia-chicken-escalope.jpg",
  "Focaccia Mortadella": "/images/dishes/focaccia-mortadella.jpg",
  "Focaccia Salame And Scamorza": "/images/dishes/focaccia-salame-and-scamorza.jpg",
  "Focaccia Slice": "/images/dishes/focaccia-slice.jpg",
  "Frittata Homemade": "/images/dishes/frittata-homemade.jpg",
  "Gnocchi Al Pesto": "/images/dishes/gnocchi-al-pesto.jpg",
  "Gnocchi Alla Sorrentina": "/images/dishes/gnocchi-alla-sorrentina.jpg",
  "Greek Yoghurt Granola": "/images/dishes/greek-yoghurt-granola.jpg",
  "Green Tea": "/images/dishes/green-tea.jpg",
  "Grilled Courgettes": "/images/dishes/grilled-courgettes.jpg",
  "Ham And Cheese Croissant": "/images/dishes/ham-and-cheese-croissant.jpg",
  "Hot Chocolate": "/images/dishes/hot-chocolate.jpg",
  "Iced Latte": "/images/dishes/iced-latte.jpg",
  "La Caprese Di Bufala": "/images/dishes/la-caprese-di-bufala.jpg",
  "La Caprese Di Burrata": "/images/dishes/la-caprese-di-burrata.jpg",
  "Lasagna Al Pesto": "/images/dishes/lasagna-al-pesto.jpg",
  "Lasagna Bolognese": "/images/dishes/lasagna-bolognese.jpg",
  "Latte": "/images/dishes/latte.jpg",
  "Leek And Potatoes Soup": "/images/dishes/leek-and-potatoes-soup.jpg",
  "Macchiato": "/images/dishes/macchiato.jpg",
  "Marinated Roast Chicken Breast With Potatoes": "/images/dishes/marinated-roast-chicken-breast-with-potatoes.jpg",
  "Matcha Latte": "/images/dishes/matcha-latte.jpg",
  "Mini Sausage And Potatoes": "/images/dishes/mini-sausage-and-potatoes.jpg",
  "Mint Tea": "/images/dishes/mint-tea.jpg",
  "Mixed Roasted Vegetables": "/images/dishes/mixed-roasted-vegetables.jpg",
  "Mocha": "/images/dishes/mocha.jpg",
  "Mozzarella And Tomato Croissant": "/images/dishes/mozzarella-and-tomato-croissant.jpg",
  "Orange Carrot Lemon Juice": "/images/dishes/orange-carrot-lemon-juice.jpg",
  "Orange Juice": "/images/dishes/orange-juice.jpg",
  "Panino Al Cotto": "/images/dishes/panino-al-cotto.jpg",
  "Panino Al Crudo": "/images/dishes/panino-al-crudo.jpg",
  "Panino Italiano - Wholegrain": "/images/dishes/panino-italiano-wholegrain.jpg",
  "Panino Salmon And Cream Cheese": "/images/dishes/panino-salmon-and-cream-cheese.jpg",
  "Panzerotto Mediterraneo": "/images/dishes/panzerotto-mediterraneo.jpg",
  "Parma Ham Platter With Focaccia": "/images/dishes/parma-ham-platter-with-focaccia.jpg",
  "Pasqualina": "/images/dishes/pasqualina.jpg",
  "Pasta Al Pesto": "/images/dishes/pasta-al-pesto.jpg",
  "Pasta Al Pomodoro": "/images/dishes/pasta-al-pomodoro.jpg",
  "Pasta Boscaiola": "/images/dishes/pasta-boscaiola.jpg",
  "Pasta Salsiccia Ragu": "/images/dishes/pasta-salsiccia-ragu.jpg",
  "Peas And Onion": "/images/dishes/peas-and-onion.jpg",
  "Peppermint Tea": "/images/dishes/peppermint-tea.jpg",
  "Piadina Mortadella": "/images/dishes/piadina-mortadella.jpg",
  "Piadina Parma Ham": "/images/dishes/piadina-parma-ham.jpg",
  "Pizza Bianca": "/images/dishes/pizza-bianca.jpg",
  "Pizza Margherita": "/images/dishes/pizza-margherita.jpg",
  "Polpette Al Pomodoro With Rice": "/images/dishes/polpette-al-pomodoro-with-rice.jpg",
  "Roast Peppers": "/images/dishes/roast-peppers.jpg",
  "Roastbeef Rocket And Parmesan": "/images/dishes/roastbeef-rocket-and-parmesan.jpg",
  "Roasted Potatoes": "/images/dishes/roasted-potatoes.jpg",
  "Scrambled Eggs On Toast": "/images/dishes/scrambled-eggs-on-toast.jpg",
  "Sourdough Sliced": "/images/dishes/sourdough-sliced.jpg",
  "Steamed Broccoli": "/images/dishes/steamed-broccoli.jpg",
  "Steamed Rice": "/images/dishes/steamed-rice.jpg",
  "Valdostana": "/images/dishes/valdostana.jpg"
} as const;
